package.json: fix digital envelope routines (#81)
In 2021, OpenSSL 3.0 deprecated a bunch of legacy algorithms that
react-scripts 4.x relied upon:

https://docs.openssl.org/3.0/man7/migration_guide/#legacy-algorithms

You can tell, because react-scripts would error out with:

	Error: error:0308010C:digital envelope routines::unsupported

This patch fixes this by upgrading to react-scripts 5.0.1